name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false   # 👈 importante! no CI não fazemos push
          tags: ci-test/app:latest

          push: true
          tags: user/app:latest

        discord:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2

            - name: Run Discord Webhook
              uses: johnnyhuy/actions-discord-git-webhook@main
              with:
                webhook_url: ${{ secrets.WEBHOOK }}

          - uses: actions/checkout@v2

          - name: Run Discord Webhook
            uses: johnnyhuy/actions-discord-git-webhook@main
            with:
              webhook_url: ${{ secrets.WEBHOOK }}
